package com.timeinc.seleniumite.junit;

/**
 MIT License

 Copyright (c) 2016 Time, Inc.

 Permission is hereby granted, free of charge, to any person obtaining a copy
 of this software and associated documentation files (the "Software"), to deal
 in the Software without restriction, including without limitation the rights
 to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 copies of the Software, and to permit persons to whom the Software is
 furnished to do so, subject to the following conditions:

 The above copyright notice and this permission notice shall be included in all
 copies or substantial portions of the Software.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 SOFTWARE.
 */

import org.openqa.selenium.remote.SessionId;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.TreeMap;

/**
 * This class is here to hold the sessionids generated by the remote webserver (when running remote)
 * so that the details of which test is which script can be tied together - needed because
 * of how paralellism is applied in the test handler
 * <p>
 * Created by cweiss1271 on 12/11/15.
 */
public class SessionRegistry {
    private static final Logger LOG = LoggerFactory.getLogger(SessionRegistry.class);
    public static SessionRegistry INSTANCE = new SessionRegistry();
    private Map<String, SessionId> registry = new TreeMap<String, SessionId>();

    private SessionRegistry() {
        super();
    }

    public SessionId lookup(String scriptName, HashMap<String, String> browserDescription) {
        SessionId rval = registry.get(createSessionKey(scriptName, browserDescription));
        if (rval == null) {
            LOG.warn("Couldn't find session for key : {} {}", scriptName, browserDescription);
        }
        return rval;
    }

    public void store(String scriptName, HashMap<String, String> browserDescription, SessionId sessionId) {
        Objects.requireNonNull(scriptName);
        Objects.requireNonNull(browserDescription);
        Objects.requireNonNull(sessionId);
        registry.put(createSessionKey(scriptName, browserDescription), sessionId);
        LOG.info("Session registry now holds {} items", registry.size());
    }

    private String createSessionKey(String scriptName, HashMap<String, String> driverDetails) {
        return scriptName + "||" + driverDetails.toString();
    }

}
